FROM node:10.13.0-alpine

COPY ../ .

ENTRYPOINT ["/action/entrypoint.sh"]

LABEL "com.github.actions.name"="Chronicler"
LABEL "com.github.actions.description"=" A better way to write your release notes."
LABEL "com.github.actions.icon"="edit-2"
LABEL "com.github.actions.color"="gray-dark"

